import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "../globals.scss";
import Header from "@/modules/header/components/Header/Header";
import { CartProvider } from "@/context/CartContext";
import Footer from "@/modules/footer/components/Footer/Footer";

export const metadata: Metadata = {
  title: "SZ - Shoes Market",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-montserrat",
});

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${montserrat.variable}`}>
        <CartProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
